# URLs for Insights section
insights_urls:
  staging:
    - "https://staging.oa.report/ORG-NAME-HERE?orgkey=ORG-KEY-HERE"
  dev:
    - "https://dev.oa.report/ORG-NAME-HERE?orgkey=ORG-KEY-HERE"

# URLs for Explore section
explore_urls:
  staging:
    - "https://staging.oa.report/ORG-NAME-HERE?orgkey=ORG-KEY-HERE"
  dev:
    - "https://dev.oa.report/ORG-NAME-HERE?orgkey=ORG-KEY-HERE"

# URLs for Actions section
actions_urls:
  staging:
    - "https://staging.oa.report/ORG-NAME-HERE?orgkey=ORG-KEY-HERE"
  dev:
    - "https://dev.oa.report/ORG-NAME-HERE?orgkey=ORG-KEY-HERE"

# XPaths for Insights extraction
xpaths:
  year_buttons: "//div[@id='year-buttons-container']/button"
  insights_cards: "//div[@id='insights_articles']//article[not(contains(@style, 'display: none'))]"
  insight_name: ".//h3"
  value: ".//span[contains(@id, 'percent_') or contains(@id, 'articles_')]"
  all_time_button: "//div[@id='year-buttons-container']/button[@id='all-time']"

# XPaths for Explore extraction
  explore_table: "//table[@id='explore_table']/tbody"
  explore_headers: "//table[@id='explore_table']/thead/tr/th"
  explore_rows: "//table[@id='explore_table']/tbody/tr"

# XPaths for Actions extraction
  actions_buttons: "//ul[@id='actions_buttons']//li[not(contains(@style, 'display: none'))]"

# Delays (in seconds)
delays:
  page_load: 2   # Time to wait after page loads
  data_load: 3   # Time to wait after clicking year buttons

# Output file names
output_file_insights: "insights_data.csv"
output_file_explore: "explore_data.csv"
output_file_actions: "actions_data.csv"

# Google Sheets settings
google_sheets:
  creds_file: config/google_creds.json

  sheets:
    insights:
      staging: api_insights_parsed_data
      dev: beta_insights_parsed_data
    explore:
      staging: api_explore_parsed_data
      dev: beta_explore_parsed_data
    actions:
      staging: api_actions_parsed_data
      dev: beta_actions_parsed_data